name: 'aiqo'

on:
  push:
    branches:
      - main
  schedule:
  - cron: '0 8 * * *' 

jobs:
  ek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'aiqicha_aqy'     
        env: 
          id: ${{secrets.ID}}
          token: ${{secrets.TOKEN}}
          pushplus: ${{secrets.PUSHPLUS}}
        run: python3 aiqo.py
